version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:2.10
    container_name: restful-api-practice-tarantool-1
    ports:
      - "3301:3301"
    volumes:
      - tarantool_data:/var/lib/tarantool
    networks:
      - tarantool-network

  api:
    build:
      context: . 
    container_name: restful-api-practice-api-1
    ports:
      - "8080:8080"
    depends_on:
      - tarantool
    networks:
      - tarantool-network

volumes:
  tarantool_data:

networks:
  tarantool-network:
    driver: bridge
